### ISSUE TITLE
JS Frameworks TL;DR

### ISSUE THREAD

**Issue by jakerella** [dcjs/talks#26]
I'd like to see a basic talk comparing the major front-end JS frameworks (React, Angular 1 & 2, Ember, maybe Vue?).

**Comment by jmdembe** [comment]
I'll take this.

**Comment by jakerella** [comment]
Awesome! How much time do you think you'll need? That is... when do you think you might be ready? And what can we do to help?

**Comment by jmdembe** [comment]
I think this would be a great half talk if this were a crash course on
frameworks. I would like at minimum a month to perfect, so I could present
in May at the very earliest.

What I will do this weekend is sent the outline that is swirling around in
my head and ask what else you would like to see discussed or added.

Does that sound good?

On Wed, Mar 15, 2017 at 7:46 PM Jordan Kasper <notifications@github.com>
wrote:

Awesome! How much time do you think you'll need? That is... when do you
think you might be ready? And what can we do to help?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dcjs/talks/issues/26#issuecomment-286915184>, or mute
the thread

**Comment by jakerella** [comment]
By "half talk" do you mean half of a DCJS meetup, like 30 min? I think there might be more content than would fit into 30 minutes.

If you want to shoot for May we could, but we're happy to have you any time. I know you just started a new gig, so I get it if this has to take a back seat.

**Comment by samuelneff** [comment]
Great talk idea. Would be nice to see specific examples that highlight best-use-case for each framework, if they exist (i.e., situation where each framework shines over others). Also any unique features that make particular things much easier in some frameworks vs others, or specific things that are difficult in some frameworks.

**Comment by jmdembe** [comment]
Noted. Thank you!

On Thu, Mar 30, 2017 at 10:06 AM, Samuel Neff <notifications@github.com>
wrote:

Great talk idea. Would be nice to see specific examples that highlight
best-use-case for each framework, if they exist (i.e., situation where each
framework shines over others). Also any unique features that make
particular things much easier in some frameworks vs others, or specific
things that are difficult in some frameworks.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dcjs/talks/issues/26#issuecomment-290421352>, or mute
the thread

**Comment by jmdembe** [comment]
Does "JS Frameworks and Libraries 101" work as a title? Also, how is this for a synopsis:

In a world where JavaScript frameworks appear every 2 seconds, come to my talk where I will give an overview on five very popular frameworks--Angular, AngularJS, React, Vue, and Ember. Come to this talk to figure out what they are, how they work, and use cases to see how these frameworks operate.

**Comment by elgreg** [comment]
TIL there's a difference between Angular and AngularJS! What about Angular 4... is that a thing we should talk about?

Title could be shorter. How about "JS Frameworks TL;DR" or something about it being a short intro to several and how they're different?

**Comment by jmdembe** [comment]
Angular 4 is grouped into Angular along with all future releases. I will talk about it, but it shouldn't be considered a separate framework from Angular.

I like JS Frameworks-TL;DR!

**Comment by jakerella** [comment]
I think the description is ok, but would like to see it expanded slightly. For example" what they are, how they work, and use cases..." is really general. In particular, "how they work" seems like weeks of instruction for each! Can we be more specific about this? I would also like to see what an attendee will come away with from this talk.

On the "Angular" vs "AngularJS" vs "Angular 2/4/37" ... as Greg pointed out, it is _not clear_ to many devs that there is a difference between "Angular" and "AngularJS". In the description, I think we need to point that out. Maybe with: "Angular (2+), AngularJS, React, ..."

**Comment by jmdembe** [comment]
I tried to incorporate feedback provided so far. Let me know what you think: 

In a world where JavaScript frameworks appear every 2 seconds, come to my talk where I will give an overview on five very popular frameworks--Angular (2+), AngularJS(1.x.x), React, Vue, and Ember. This talk will help you understand the basics about each of these frameworks and why you would choose one framework of another.

**Comment by jakerella** [comment]
I think this is good for us. Just as an FYI if you were to shop this around to other user groups or conferences, I think you need to expand the abstract (description) quite a bit. Most places want more information about what, exactly, you'll be covering, why this matters, what attendees will get out of the talk (a bit more so than you have), and possibly a bit on what you are _not_ covering (to set expectations).

For example, in your abstract I would include the fact that you will discuss business use cases and examples of companies choosing one over another. If you plan to show code, to what degree? How in depth?

Like I said, this will work for us, but you wanted to shop this talk around you'd want to expand on this!

**Comment by jmdembe** [comment]
Will do. Thank you!

**Comment by asabaylus** [comment]
@jmdembe can you give me your Bio?

**Comment by jmdembe** [comment]
Jessica Dembe is an Associate Technical Consultant with Blackstone
Technology Group. Her work is with using JavaScript to enhance the user
experience for government clients. When she is not on the clock, she is
exploring as many peanut-free restaurants that she can find, trying a new
recipe, and figuring out how to get into exercise again.
