### ISSUE TITLE
WANTED: PWA and Serviceworkers

### ISSUE THREAD

**Issue by elgreg** [dcjs/talks#50]

**Comment by jackkoppa** [comment]
Hi @elgreg. I'd be happy to give a lightning talk-length presentation on my PWA [cityaq](https://github.com/jackkoppa/cityaq). Some of my service worker lessons have been Angular-specific, but a lot of the ups & downs have just been general PWA learning. I actually gave a [similar talk in Milwaukee](https://youtu.be/jIWHCbtN2NM?t=14s); the project has evolved since that point. I'll submit for the August 9th meetup.

**Comment by jackkoppa** [comment]
(submitted proposed talk for the August 9th meetup [here](https://github.com/dcjs/talks/issues/54))

**Comment by elgreg** [comment]
Awesome!
